attributes:
  endpoint:
    value: ''
    label: 'GlusterFS endpoint'
    description: 'IP address of GlusterFS endpoint'
    weight: 25
    type: "text"
    regex:
      source: '^([a-zA-Z0-9]+[-\.])*[a-zA-Z0-9]+\:(\d{1,5}\:){0,1}\/[a-zA-Z0-9-_\.]*$'
      error: "Invalid address"
