attributes:
  endpoint:
    value: ''
    label: 'GlusterFS endpoint'
    description: 'IP address of GlusterFS endpoint'
    weight: 25
    type: "text"
    regex:
      source: '^([a-zA-Z0-9]+[-\.])*[a-zA-Z0-9]+\:(([1-9][0-9]{0,3}|[1-6][0-5][0-5][0-3][0-5])\:){0,1}\/[a-zA-Z0-9-_\.]*\w+$'
      error: "Invalid address"
